import os
import re
from datetime import datetime
from decimal import Decimal
from app import app, db
from models import Ingredient, IngredientPrice

def normalize_ingredient_name(name):
    original_name = name
    name = name.lower()

    # Remove text in parentheses
    name = re.sub(r'\s*\(.*?\)', '', name).strip()
    # Remove text after a comma
    name = re.sub(r',.*', '', name).strip()

    # Remove common quantity/unit prefixes and descriptive words
    name = re.sub(r'(\d+\s*(?:cup|teaspoon|tablespoon|oz|g|lb|pinch|dash)?s?\b)?', '', name).strip()
    name = re.sub(r'(?:all-purpose|mashed|overripe|large|medium|small|chopped|sliced|beaten|softened|whole|dried|canned|cooked|fresh|ribs of|package|box|bag|tsp\.|tbsp\.|~|½|¼|\*boiling\*|stale|toasted|for serving|for the batter|for the syrup|or 2|just enough to cook the|leftovers are perfect|in oil or water|condensed|if available|as needed|plus more as needed|to taste|peeled and sliced/cubed|sliced thin|chopped|sliced|beaten|softened|whole milk is best|or bacon fat|or bacon grease, melted|or margarine|or oil|for the roux|or paprika|or 1 can sausage/meat|or mixed beans|or stock|or broth|or milk|or egg noodles|or 1/2 cup canned|if not using dried|navy or pinto|with buttered white bread|the "shingle"|the "shingle"|into small pieces|chipped or torn)\s*', '', name).strip()
    
    # Specific replacements for better matching
    name = name.replace('all-purpose flour', 'flour')
    name = name.replace('mashed overripe bananas', 'banana')
    name = name.replace('bag egg noodles', 'egg noodles')
    name = name.replace('creamed corn', 'corn')
    name = name.replace('campbell\'s chicken noodle soup', 'chicken noodle soup')
    name = name.replace('dried beef', 'beef')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('honey maple syrup', 'honey')
    name = name.replace('tuna fish', 'tuna')
    name = name.replace('fat', 'lard') # Normalize fat to lard if it's a general fat
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('meat stock or water', 'meat stock')
    name = name.replace('dried beans', 'beans')
    name = name.replace('chicken stock', 'broth')
    name = name.replace('canned tomatoes', 'tomato')
    name = name.replace('canned tuna fish', 'tuna')
    name = name.replace('hard-boiled eggs', 'eggs')
    name = name.replace('stale bread', 'bread')
    name = name.replace('flour for the roux', 'flour')
    name = name.replace('caraway seeds or paprika', 'caraway seeds')
    name = name.replace('water or broth', 'water')
    name = name.replace('for the dumplings', '')
    name = name.replace('or eggs', 'eggs')
    name = name.replace('flour or enough to make a thick batter', 'flour')
    name = name.replace('pinch of salt', 'salt')
    name = name.replace('cloves garlic', 'garlic')
    name = name.replace('meat stock or water', 'meat stock')
    name = name.replace('bacon grease', 'lard')
    name = name.replace('dried beans', 'beans')
    name = name.replace('chicken noodle soup', 'chicken noodle soup')
    name = name.replace('dried beef', 'beef')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('boiling water', 'water')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned corn', 'corn')
    name = name.replace('canned peas', 'peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('stock', 'broth')
    name = name.replace('tuna fish', 'tuna')
    name = name.replace('paprika', 'paprika')
    name = name.replace('can of meat sausage', 'meat')
    name = name.replace('hot dogs sliced', 'hot dogs')
    name = name.replace('tomato chopped', 'tomato')
    name = name.replace('onion chopped', 'onion')
    name = name.replace('carrots sliced', 'carrots')
    name = name.replace('potatoes sliced', 'potatoes')
    name = name.replace('milk enough to cover the potatoes', 'milk')
    name = name.replace('cooked rice', 'rice')
    name = name.replace('honey maple syrup or molasses', 'honey')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('raisins', 'raisins')
    name = name.replace('celery', 'celery')
    name = name.replace('canned tuna', 'tuna')
    name = name.replace('hard-boiled eggs', 'eggs')
    name = name.replace('bread', 'bread')
    name = name.replace('fat', 'lard')
    name = name.replace('flour', 'flour')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('eggs', 'eggs')
    name = name.replace('salt', 'salt')
    name = name.replace('garlic', 'garlic')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('meat stock', 'meat stock')
    name = name.replace('lard', 'lard')
    name = name.replace('beans', 'beans')
    name = name.replace('chicken noodle soup', 'chicken noodle soup')
    name = name.replace('beef', 'beef')
    name = name.replace('sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name.replace('oil', 'oil')
    name = name.replace('eggs', 'eggs')
    name = name.replace('banana', 'banana')
    name = name.replace('beef', 'beef')
    name = name.replace('chicken', 'chicken')
    name = name.replace('pork', 'pork')
    name = name.replace('tuna', 'tuna')
    name = name.replace('hot dogs', 'hot dogs')
    name = name.replace('meat', 'meat')
    name = name.replace('noodles', 'noodles')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned tomatoes', 'canned tomatoes')
    name = name.replace('canned corn', 'canned corn')
    name = name.replace('canned peas', 'canned peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('dried beans', 'dried beans')
    name = name.replace('raisins', 'raisins')
    name = name.replace('bread', 'bread')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('stock', 'stock')
    name = name.replace('soup', 'soup')
    name = name.replace('cream', 'cream')
    name = name.replace('tomato', 'tomato')
    name = name.replace('corn', 'corn')
    name = name.replace('peas', 'peas')
    name = name.replace('beans', 'beans')
    name = name.replace('molasses', 'molasses')
    name = name.replace('honey', 'honey')
    name = name.replace('syrup', 'syrup')
    name = name.replace('sugar', 'sugar')
    name = name.replace('brown sugar', 'brown sugar')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name.replace('oil', 'oil')
    name = name.replace('eggs', 'eggs')
    name = name.replace('banana', 'banana')
    name = name.replace('beef', 'beef')
    name = name.replace('chicken', 'chicken')
    name = name.replace('pork', 'pork')
    name = name.replace('tuna', 'tuna')
    name = name.replace('hot dogs', 'hot dogs')
    name = name.replace('meat', 'meat')
    name = name.replace('noodles', 'noodles')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned tomatoes', 'canned tomatoes')
    name = name.replace('canned corn', 'canned corn')
    name = name.replace('canned peas', 'canned peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('dried beans', 'dried beans')
    name = name.replace('raisins', 'raisins')
    name = name.replace('bread', 'bread')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('stock', 'stock')
    name = name.replace('soup', 'soup')
    name = name.replace('cream', 'cream')
    name = name.replace('tomato', 'tomato')
    name = name.replace('corn', 'corn')
    name = name.replace('peas', 'peas')
    name = name.replace('beans', 'beans')
    name = name.replace('molasses', 'molasses')
    name = name.replace('honey', 'honey')
    name = name.replace('syrup', 'syrup')
    name = name.replace('sugar', 'sugar')
    name = name.replace('brown sugar', 'brown sugar')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name.replace('oil', 'oil')
    name = name.replace('eggs', 'eggs')
    name = name.replace('banana', 'banana')
    name = name.replace('beef', 'beef')
    name = name.replace('chicken', 'chicken')
    name = name.replace('pork', 'pork')
    name = name.replace('tuna', 'tuna')
    name = name.replace('hot dogs', 'hot dogs')
    name = name.replace('meat', 'meat')
    name = name.replace('noodles', 'noodles')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned tomatoes', 'canned tomatoes')
    name = name.replace('canned corn', 'canned corn')
    name = name.replace('canned peas', 'canned peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('dried beans', 'dried beans')
    name = name.replace('raisins', 'raisins')
    name = name.replace('bread', 'bread')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('stock', 'stock')
    name = name.replace('soup', 'soup')
    name = name.replace('cream', 'cream')
    name = name.replace('tomato', 'tomato')
    name = name.replace('corn', 'corn')
    name = name.replace('peas', 'peas')
    name = name.replace('beans', 'beans')
    name = name.replace('molasses', 'molasses')
    name = name.replace('honey', 'honey')
    name = name.replace('syrup', 'syrup')
    name = name.replace('sugar', 'sugar')
    name = name.replace('brown sugar', 'brown sugar')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name.replace('oil', 'oil')
    name = name.replace('eggs', 'eggs')
    name = name.replace('banana', 'banana')
    name = name.replace('beef', 'beef')
    name = name.replace('chicken', 'chicken')
    name = name.replace('pork', 'pork')
    name = name.replace('tuna', 'tuna')
    name = name.replace('hot dogs', 'hot dogs')
    name = name.replace('meat', 'meat')
    name = name.replace('noodles', 'noodles')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned tomatoes', 'canned tomatoes')
    name = name.replace('canned corn', 'canned corn')
    name = name.replace('canned peas', 'canned peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('dried beans', 'dried beans')
    name = name.replace('raisins', 'raisins')
    name = name.replace('bread', 'bread')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('stock', 'stock')
    name = name.replace('soup', 'soup')
    name = name.replace('cream', 'cream')
    name = name.replace('tomato', 'tomato')
    name = name.replace('corn', 'corn')
    name = name.replace('peas', 'peas')
    name = name.replace('beans', 'beans')
    name = name.replace('molasses', 'molasses')
    name = name.replace('honey', 'honey')
    name = name.replace('syrup', 'syrup')
    name = name.replace('sugar', 'sugar')
    name = name.replace('brown sugar', 'brown sugar')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name.replace('oil', 'oil')
    name = name.replace('eggs', 'eggs')
    name = name.replace('banana', 'banana')
    name = name.replace('beef', 'beef')
    name = name.replace('chicken', 'chicken')
    name = name.replace('pork', 'pork')
    name = name.replace('tuna', 'tuna')
    name = name.replace('hot dogs', 'hot dogs')
    name = name.replace('meat', 'meat')
    name = name.replace('noodles', 'noodles')
    name = name.replace('macaroni', 'macaroni')
    name = name.replace('egg noodles', 'egg noodles')
    name = name.replace('canned tomatoes', 'canned tomatoes')
    name = name.replace('canned corn', 'canned corn')
    name = name.replace('canned peas', 'canned peas')
    name = name.replace('mixed beans', 'mixed beans')
    name = name.replace('dried beans', 'dried beans')
    name = name.replace('raisins', 'raisins')
    name = name.replace('bread', 'bread')
    name = name.replace('water', 'water')
    name = name.replace('broth', 'broth')
    name = name.replace('stock', 'stock')
    name = name.replace('soup', 'soup')
    name = name.replace('cream', 'cream')
    name = name.replace('tomato', 'tomato')
    name = name.replace('corn', 'corn')
    name = name.replace('peas', 'peas')
    name = name.replace('beans', 'beans')
    name = name.replace('molasses', 'molasses')
    name = name.replace('honey', 'honey')
    name = name.replace('syrup', 'syrup')
    name = name.replace('sugar', 'sugar')
    name = name.replace('brown sugar', 'brown sugar')
    name = name.replace('white sugar', 'sugar')
    name = name.replace('baking powder', 'baking powder')
    name = name.replace('baking soda', 'baking soda')
    name = name.replace('salt', 'salt')
    name = name.replace('cinnamon', 'cinnamon')
    name = name.replace('vanilla', 'vanilla')
    name = name.replace('caraway seeds', 'caraway seeds')
    name = name.replace('paprika', 'paprika')
    name = name.replace('garlic', 'garlic')
    name = name.replace('onion', 'onion')
    name = name.replace('celery', 'celery')
    name = name.replace('carrots', 'carrots')
    name = name.replace('potatoes', 'potatoes')
    name = name.replace('rice', 'rice')
    name = name.replace('cornmeal', 'cornmeal')
    name = name.replace('flour', 'flour')
    name = name.replace('milk', 'milk')
    name = name.replace('butter', 'butter')
    name = name.replace('lard', 'lard')
    name = name = re.sub(r'\s+', ' ', name).strip() # Replace multiple spaces with single space

    return name.lower()


def assign_prices():
    with app.app_context():
        # Define some mock prices for common ingredients
        # In a real scenario, these would come from an external API
        mock_prices = {
            "flour": Decimal("0.50"), # per cup
            "baking soda": Decimal("0.05"), # per tsp
            "salt": Decimal("0.02"), # per tsp
            "cinnamon": Decimal("0.10"), # per tsp
            "brown sugar": Decimal("0.30"), # per cup
            "butter": Decimal("1.00"), # per 1/2 cup
            "eggs": Decimal("0.20"), # per large egg
            "banana": Decimal("0.40"), # per banana
            "ground beef": Decimal("5.00"), # per lb
            "egg noodles": Decimal("1.50"), # per bag
            "creamed corn": Decimal("0.75"), # per can
            "milk": Decimal("0.15"), # per cup
            "potatoes": Decimal("0.25"), # per medium potato
            "onion": Decimal("0.30"), # per onion
            "carrots": Decimal("0.20"), # per carrot
            "rice": Decimal("0.20"), # per cup
            "honey": Decimal("0.50"), # per Tbsp
            "molasses": Decimal("0.40"), # per Tbsp
            "tuna": Decimal("1.20"), # per can
            "celery": Decimal("0.20"), # per rib
            "hot dogs": Decimal("0.50"), # per hot dog
            "dried beans": Decimal("0.80"), # per package
            "lard": Decimal("0.20"), # per Tbsp
            "tomato": Decimal("0.40"), # per tomato
            "dried beef": Decimal("3.00"), # per oz
            "bread": Decimal("0.10"), # per slice
            "water": Decimal("0.00"), # free
            "oil": Decimal("0.10"), # per Tbsp
            "baking powder": Decimal("0.05"), # per tsp
            "raisins": Decimal("0.20"), # per 1/2 cup
            "macaroni": Decimal("0.80"), # per box
            "canned tomatoes": Decimal("0.60"), # per can
            "corn": Decimal("0.70"), # per can
            "peas": Decimal("0.70"), # per can
            "mixed beans": Decimal("0.70"), # per can
            "broth": Decimal("0.20"), # per cup
            "vanilla": Decimal("0.10"), # per tsp
            "caraway seeds": Decimal("0.05"), # per tsp
            "paprika": Decimal("0.05"), # per tsp
            "garlic": Decimal("0.10"), # per clove
            "cornmeal": Decimal("0.30"), # per cup
            "meat stock": Decimal("0.50"), # per cup
            "chicken noodle soup": Decimal("1.00"), # per can
            "chicken stock": Decimal("0.50"), # per cup
            "sugar": Decimal("0.25"), # per cup
            "canned vegetables": Decimal("0.70"), # per can
            "canned meat": Decimal("1.50"), # per can
        }

        for ingredient_db in Ingredient.query.all():
            normalized_name = normalize_ingredient_name(ingredient_db.name)
            price_value = mock_prices.get(normalized_name)

            if price_value is not None:
                ingredient_price = IngredientPrice.query.filter_by(ingredient_id=ingredient_db.id).first()
                if ingredient_price:
                    ingredient_price.price = price_value
                    ingredient_price.last_updated = datetime.now()
                    print(f"Updated price for '{ingredient_db.name}' (normalized to '{normalized_name}'): {price_value}")
                else:
                    new_price = IngredientPrice(
                        ingredient_id=ingredient_db.id,
                        price=price_value,
                        currency='USD',
                        last_updated=datetime.now()
                    )
                    db.session.add(new_price)
                    print(f"Assigned price for '{ingredient_db.name}' (normalized to '{normalized_name}'): {price_value}")
            else:
                print(f"No mock price found for '{ingredient_db.name}' (normalized to '{normalized_name}'). Skipping.")
        
        db.session.commit()
        print("Mock prices assigned/updated successfully.")

if __name__ == '__main__':
    assign_prices()
