"""Add short_description to Recipe

Revision ID: 5b2a1da750b4
Revises: 0af352bab7c4
Create Date: 2025-11-14 18:59:18.089978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a1da750b4'
down_revision: Union[str, Sequence[str], None] = '0af352bab7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('short_description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'short_description')
    # ### end Alembic commands ###
