"""Increase quantity field size

Revision ID: 748388e3b341
Revises: e51d7bd11876
Create Date: 2025-11-14 19:21:22.361365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '748388e3b341'
down_revision: Union[str, Sequence[str], None] = 'e51d7bd11876'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredient', 'quantity',
                    existing_type=sa.String(length=50),
                    type_=sa.String(length=500),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipe_ingredient', 'quantity',
                    existing_type=sa.String(length=500),
                    type_=sa.String(length=50),
                    existing_nullable=True)
    # ### end Alembic commands ###
