"""Update pricing model with imperial units

Revision ID: e51d7bd11876
Revises: 5b2a1da750b4
Create Date: 2025-11-14 19:09:08.175059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51d7bd11876'
down_revision: Union[str, Sequence[str], None] = '5b2a1da750b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with defaults first
    op.add_column('ingredient_price', sa.Column('unit', sa.String(length=20), nullable=True))
    op.add_column('ingredient_price', sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('ingredient_price', sa.Column('region', sa.String(length=50), nullable=True))
    
    # Set default values for existing rows
    op.execute("UPDATE ingredient_price SET unit = 'lb' WHERE unit IS NULL")
    op.execute("UPDATE ingredient_price SET quantity = 1.0 WHERE quantity IS NULL")
    op.execute("UPDATE ingredient_price SET region = 'US' WHERE region IS NULL")
    
    # Now make columns NOT NULL
    op.alter_column('ingredient_price', 'unit', nullable=False)
    op.alter_column('ingredient_price', 'quantity', nullable=False)
    op.alter_column('ingredient_price', 'region', nullable=False)
    
    op.drop_constraint(op.f('ingredient_price_ingredient_id_key'), 'ingredient_price', type_='unique')
    op.add_column('recipe_ingredient', sa.Column('amount', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('recipe_ingredient', sa.Column('unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredient', 'unit')
    op.drop_column('recipe_ingredient', 'amount')
    op.create_unique_constraint(op.f('ingredient_price_ingredient_id_key'), 'ingredient_price', ['ingredient_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('ingredient_price', 'region')
    op.drop_column('ingredient_price', 'quantity')
    op.drop_column('ingredient_price', 'unit')
    # ### end Alembic commands ###
