"""Add story and economic_lesson to Recipe

Revision ID: ed77e966af6c
Revises: ef619289ed19
Create Date: 2025-11-14 18:25:26.317498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed77e966af6c'
down_revision: Union[str, Sequence[str], None] = 'ef619289ed19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('story', sa.Text(), nullable=True))
    op.add_column('recipe', sa.Column('economic_lesson', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'economic_lesson')
    op.drop_column('recipe', 'story')
    # ### end Alembic commands ###
